name: Deploy Spring Boot to Sealos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

#      - name: Build and Push Docker Image with Jib
#        run: |
#          mvn clean package jib:build -DskipTests \
#            -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
#            -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

#      - name: Configure Kubeconfig
#        run: |
#          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
#          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube # 确保 .kube 目录存在
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config view
#      - name: Configure Kubeconfig
#        run: |
#          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
#          kubectl config view

      - name: Verify Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Update Deployment Image in Sealos
        run: |
          kubectl set image deployment/hello-world-1 hello-world-1-container=lsx8629303/location-service:latest -n default
          kubectl rollout status deployment/hello-world-1 -n default

      - name: Clean up
        run: rm -f kubeconfig